/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as BucketsRouteImport } from './routes/buckets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeysIdRouteImport } from './routes/keys.$id'
import { Route as BucketsIdRouteImport } from './routes/buckets.$id'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsRoute = BucketsRouteImport.update({
  id: '/buckets',
  path: '/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIdRoute = KeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KeysRoute,
} as any)
const BucketsIdRoute = BucketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BucketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/keys': typeof KeysRouteWithChildren
  '/layout': typeof LayoutRoute
  '/workers': typeof WorkersRoute
  '/buckets/$id': typeof BucketsIdRoute
  '/keys/$id': typeof KeysIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/keys': typeof KeysRouteWithChildren
  '/layout': typeof LayoutRoute
  '/workers': typeof WorkersRoute
  '/buckets/$id': typeof BucketsIdRoute
  '/keys/$id': typeof KeysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buckets': typeof BucketsRouteWithChildren
  '/keys': typeof KeysRouteWithChildren
  '/layout': typeof LayoutRoute
  '/workers': typeof WorkersRoute
  '/buckets/$id': typeof BucketsIdRoute
  '/keys/$id': typeof KeysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buckets'
    | '/keys'
    | '/layout'
    | '/workers'
    | '/buckets/$id'
    | '/keys/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buckets'
    | '/keys'
    | '/layout'
    | '/workers'
    | '/buckets/$id'
    | '/keys/$id'
  id:
    | '__root__'
    | '/'
    | '/buckets'
    | '/keys'
    | '/layout'
    | '/workers'
    | '/buckets/$id'
    | '/keys/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BucketsRoute: typeof BucketsRouteWithChildren
  KeysRoute: typeof KeysRouteWithChildren
  LayoutRoute: typeof LayoutRoute
  WorkersRoute: typeof WorkersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets': {
      id: '/buckets'
      path: '/buckets'
      fullPath: '/buckets'
      preLoaderRoute: typeof BucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/$id': {
      id: '/keys/$id'
      path: '/$id'
      fullPath: '/keys/$id'
      preLoaderRoute: typeof KeysIdRouteImport
      parentRoute: typeof KeysRoute
    }
    '/buckets/$id': {
      id: '/buckets/$id'
      path: '/$id'
      fullPath: '/buckets/$id'
      preLoaderRoute: typeof BucketsIdRouteImport
      parentRoute: typeof BucketsRoute
    }
  }
}

interface BucketsRouteChildren {
  BucketsIdRoute: typeof BucketsIdRoute
}

const BucketsRouteChildren: BucketsRouteChildren = {
  BucketsIdRoute: BucketsIdRoute,
}

const BucketsRouteWithChildren =
  BucketsRoute._addFileChildren(BucketsRouteChildren)

interface KeysRouteChildren {
  KeysIdRoute: typeof KeysIdRoute
}

const KeysRouteChildren: KeysRouteChildren = {
  KeysIdRoute: KeysIdRoute,
}

const KeysRouteWithChildren = KeysRoute._addFileChildren(KeysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BucketsRoute: BucketsRouteWithChildren,
  KeysRoute: KeysRouteWithChildren,
  LayoutRoute: LayoutRoute,
  WorkersRoute: WorkersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
