/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeysIndexRouteImport } from './routes/keys.index'
import { Route as BucketsIndexRouteImport } from './routes/buckets.index'
import { Route as KeysIdRouteImport } from './routes/keys.$id'
import { Route as BucketsIdRouteImport } from './routes/buckets.$id'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIndexRoute = KeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIndexRoute = BucketsIndexRouteImport.update({
  id: '/buckets/',
  path: '/buckets/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIdRoute = KeysIdRouteImport.update({
  id: '/keys/$id',
  path: '/keys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketsIdRoute = BucketsIdRouteImport.update({
  id: '/buckets/$id',
  path: '/buckets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/layout': typeof LayoutRoute
  '/workers': typeof WorkersRoute
  '/buckets/$id': typeof BucketsIdRoute
  '/keys/$id': typeof KeysIdRoute
  '/buckets/': typeof BucketsIndexRoute
  '/keys/': typeof KeysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/layout': typeof LayoutRoute
  '/workers': typeof WorkersRoute
  '/buckets/$id': typeof BucketsIdRoute
  '/keys/$id': typeof KeysIdRoute
  '/buckets': typeof BucketsIndexRoute
  '/keys': typeof KeysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/layout': typeof LayoutRoute
  '/workers': typeof WorkersRoute
  '/buckets/$id': typeof BucketsIdRoute
  '/keys/$id': typeof KeysIdRoute
  '/buckets/': typeof BucketsIndexRoute
  '/keys/': typeof KeysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/layout'
    | '/workers'
    | '/buckets/$id'
    | '/keys/$id'
    | '/buckets/'
    | '/keys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/layout'
    | '/workers'
    | '/buckets/$id'
    | '/keys/$id'
    | '/buckets'
    | '/keys'
  id:
    | '__root__'
    | '/'
    | '/layout'
    | '/workers'
    | '/buckets/$id'
    | '/keys/$id'
    | '/buckets/'
    | '/keys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  WorkersRoute: typeof WorkersRoute
  BucketsIdRoute: typeof BucketsIdRoute
  KeysIdRoute: typeof KeysIdRoute
  BucketsIndexRoute: typeof BucketsIndexRoute
  KeysIndexRoute: typeof KeysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/': {
      id: '/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof KeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/': {
      id: '/buckets/'
      path: '/buckets'
      fullPath: '/buckets/'
      preLoaderRoute: typeof BucketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/$id': {
      id: '/keys/$id'
      path: '/keys/$id'
      fullPath: '/keys/$id'
      preLoaderRoute: typeof KeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buckets/$id': {
      id: '/buckets/$id'
      path: '/buckets/$id'
      fullPath: '/buckets/$id'
      preLoaderRoute: typeof BucketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  WorkersRoute: WorkersRoute,
  BucketsIdRoute: BucketsIdRoute,
  KeysIdRoute: KeysIdRoute,
  BucketsIndexRoute: BucketsIndexRoute,
  KeysIndexRoute: KeysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
